name: Dev-Build

on:
  push:
  schedule:
    - cron:  '21 21 * * *'
  workflow_dispatch:

jobs:
  build:
    uses: axonivy-market/github-workflows/.github/workflows/dev.yml@v21
    with:
      mvnArgs: '-X' #try passthrough
      ivyVersion: 'nightly-11.1'
